# Generated by Django 4.0.4 on 2022-06-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_bg',
            field=models.ImageField(default=0, upload_to='bg'),
            preserve_default=False,
        ),
    ]
