# Generated by Django 4.0.4 on 2022-06-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0004_alter_movie_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='lowVideo',
            field=models.ManyToManyField(to='netflixapp.videolow'),
        ),
    ]
